export default {
    PUSH_NAV_FROM: 'PUSH_NAV_FROM',
    PUSH_NAV_TRANSITION: 'PUSH_NAV_TRANSITION',
    PUSH_STEP: 'PUSH_STEP',
    COMMIT_DATA: 'COMMIT_DATA',
    FETCH_QUESTION: 'FETCH_QUESTION'
}
